"""Capabilities required by the engine; implemented by agent-kit registries."""
from typing import Protocol
from covalent_contracts.agent import AgentSpec
from covalent_contracts.skill import SkillSpec
from covalent_contracts.model import ProviderConfig
from covalent_runtime.domain.types import RunContext, ToolCall, ToolResult
from covalent_runtime.domain.tooling import ToolDefinition
from covalent_runtime.ports.model import ModelAdapter

class RuntimeRegistry(Protocol):
    agents: dict[str, AgentSpec]
    skills: dict[str, SkillSpec]
    local_tools: dict[str, ToolDefinition]

    def is_skill_enabled(self, name: str) -> bool: ...
    def skill_prompt_index(self, name: str) -> str: ...
    def get_agent(self, name: str) -> AgentSpec: ...
    def get_model_provider(self, config: ProviderConfig) -> ModelAdapter: ...
    def normalize_mcp_tool_name(self, name: str) -> str: ...
    def display_mcp_tool_name(self, name: str) -> str: ...
    async def resolve_tools_for_agent(self, agent: AgentSpec) -> list[dict]: ...
    async def execute_tool_call(self, agent: AgentSpec, call: ToolCall, context: RunContext | None = None) -> ToolResult: ...
