"""Persistence boundary for durable runs, independent of database/HTTP libraries."""
from datetime import datetime
from typing import Any, Protocol


class RunRecord(Protocol):
    id: str
    session_id: str
    agent_name: str
    status: str
    owner_user_id: str | None
    workspace_id: str | None
    created_at: datetime
    finished_at: datetime | None


class RunStore(Protocol):
    async def create_run(self, *, run_id: str, session_id: str, agent_name: str,
                         owner_user_id: str | None, workspace_id: str | None,
                         input_json: dict[str, Any]) -> int: ...
    async def finish_run(self, run_id: str, status: str, error: dict[str, Any] | None = None) -> None: ...
    async def append_event(self, run_id: str, event_name: str, payload: dict[str, Any], position: int) -> None: ...
    async def get_run(self, run_id: str) -> RunRecord | None: ...
    async def open_run_for_session(self, session_id: str) -> RunRecord | None: ...
    async def list_runs_for_session(self, session_id: str) -> list[RunRecord]: ...
    async def mark_cancelling(self, run_id: str) -> None: ...
    async def events_after(self, run_id: str, after_position: int) -> list[tuple[int, str, dict[str, Any]]]: ...
    async def stale_run_ids(self) -> list[str]: ...
