"""Tests for chat attachment extraction from tool results.

Covers both paths of `_published_download_attachments_from_tool_results`:
the legacy publish_downloadable_file whole-content JSON and the structured
`download_artifacts` payload emitted for browser_screenshot — plus error
filtering, kind mapping, and dedup via `_append_assistant_attachments`.
"""

from __future__ import annotations

import json
import unittest

from covalent.application.services.session_service import (
    _append_assistant_attachments,
    _attachment_metadata_key,
    _published_download_attachments_from_tool_results,
)
from covalent.infra.memory import ChatTranscriptMessage


def _publish_content(name: str = "story.html", content_type: str = "text/html") -> str:
    return json.dumps(
        {
            "id": f"download-{name}",
            "name": name,
            "size": 128,
            "content_type": content_type,
            "workspace_path": f".covalent/downloads/s1/{name}",
            "download_url": f"/api/backend/downloads/s1/{name}",
            "download_markdown": f"[Download {name}](/api/backend/downloads/s1/{name})",
            "summary": "Generated by the agent and ready to download.",
            "published_at": "2026-09-22T00:00:00+00:00",
        },
        ensure_ascii=False,
        indent=2,
    )


def _artifact(name: str = "screenshot-20260922-010203.png", content_type: str = "image/png") -> dict:
    return {
        "id": f"download-{name}",
        "name": name,
        "size": 4096,
        "content_type": content_type,
        "download_url": f"/api/backend/downloads/s1/{name}",
        "download_markdown": f"[Download {name}](/api/backend/downloads/s1/{name})",
        "summary": "Screenshot of https://example.com/ (viewport)",
    }


def _payload(*results: dict) -> dict:
    return {"results": list(results)}


class PublishedDownloadAttachmentTests(unittest.TestCase):
    def test_legacy_publish_content_json_parsed(self) -> None:
        attachments = _published_download_attachments_from_tool_results(
            _payload({"name": "publish_downloadable_file", "content": _publish_content()})
        )
        self.assertEqual(len(attachments), 1)
        self.assertEqual(attachments[0]["name"], "story.html")
        self.assertEqual(attachments[0]["kind"], "text")
        self.assertEqual(attachments[0]["download_url"], "/api/backend/downloads/s1/story.html")

    def test_download_artifacts_parsed(self) -> None:
        attachments = _published_download_attachments_from_tool_results(
            _payload({"name": "browser_screenshot", "download_artifacts": [_artifact()]})
        )
        self.assertEqual(len(attachments), 1)
        self.assertEqual(attachments[0]["kind"], "image")
        self.assertEqual(attachments[0]["content_type"], "image/png")
        self.assertEqual(attachments[0]["summary"], "Screenshot of https://example.com/ (viewport)")

    def test_error_results_skipped_for_both_paths(self) -> None:
        attachments = _published_download_attachments_from_tool_results(
            _payload(
                {"name": "publish_downloadable_file", "is_error": True, "content": _publish_content()},
                {"name": "browser_screenshot", "is_error": True, "download_artifacts": [_artifact()]},
            )
        )
        self.assertEqual(attachments, [])

    def test_artifacts_without_name_or_url_ignored(self) -> None:
        attachments = _published_download_attachments_from_tool_results(
            _payload(
                {"name": "browser_screenshot", "download_artifacts": [{"name": "x"}, {"download_url": "/y"}, "junk", _artifact()]}
            )
        )
        self.assertEqual(len(attachments), 1)

    def test_non_publish_tool_without_artifacts_ignored(self) -> None:
        attachments = _published_download_attachments_from_tool_results(
            _payload({"name": "run_shell", "content": _publish_content()})
        )
        self.assertEqual(attachments, [])

    def test_mixed_results_keep_order(self) -> None:
        attachments = _published_download_attachments_from_tool_results(
            _payload(
                {"name": "run_shell", "content": "ok"},
                {"name": "browser_screenshot", "download_artifacts": [_artifact()]},
                {"name": "publish_downloadable_file", "content": _publish_content(content_type="application/pdf", name="doc.pdf")},
            )
        )
        self.assertEqual([a["name"] for a in attachments], ["screenshot-20260922-010203.png", "doc.pdf"])
        self.assertEqual([a["kind"] for a in attachments], ["image", "pdf"])


class AppendAssistantAttachmentsTests(unittest.TestCase):
    def test_appends_to_last_assistant_message(self) -> None:
        messages = [ChatTranscriptMessage(id="m1", role="assistant", content="hi")]
        _append_assistant_attachments(messages, "m1", [{"id": "a1", "name": "shot.png"}])
        self.assertEqual(messages[0].attachments, [{"id": "a1", "name": "shot.png"}])

    def test_duplicates_collapse_by_metadata_key(self) -> None:
        messages = [ChatTranscriptMessage(id="m1", role="assistant", content="hi")]
        attachment = {"id": "a1", "name": "shot.png", "download_url": "/d/s1/shot.png"}
        replayed = dict(attachment, size=4096, kind="image")
        _append_assistant_attachments(messages, "m1", [attachment])
        _append_assistant_attachments(messages, "m1", [replayed])
        self.assertEqual(len(messages[0].attachments), 1)
        self.assertEqual(_attachment_metadata_key(messages[0].attachments[0]), "a1")

    def test_empty_attachments_noop(self) -> None:
        messages: list[ChatTranscriptMessage] = []
        _append_assistant_attachments(messages, "m1", [])
        self.assertEqual(messages, [])


if __name__ == "__main__":
    unittest.main()
