import { useEffect, useRef, useState } from "react";
import type { EChartsOption } from "echarts";

export function ChartBlock({ source }: { source: string }) {
  const element = useRef<HTMLDivElement>(null);
  const [invalid, setInvalid] = useState(false);
  useEffect(() => {
    if (!element.current) return;
    setInvalid(false);
    let disposed = false;
    let cleanup: (() => void) | undefined;
    try {
      const option = JSON.parse(source) as EChartsOption;
      void import("echarts").then((echarts) => {
        if (disposed || !element.current) return;
        try {
          const chart = echarts.init(element.current);
          chart.setOption(option);
          const observer = new ResizeObserver(() => chart.resize());
          observer.observe(element.current);
          cleanup = () => { observer.disconnect(); chart.dispose(); };
        } catch { setInvalid(true); }
      }).catch(() => setInvalid(true));
    } catch {
      setInvalid(true);
      return;
    }
    return () => {
      disposed = true;
      cleanup?.();
    };
  }, [source]);
  if (invalid) return <pre className="chat-chart-fallback">{source}</pre>;
  return (
    <div
      className="chat-chart"
      ref={element}
      role="img"
      aria-label="Chart generated by the Agent"
    />
  );
}
