"""Server-Sent Event event-name constants shared by the API layer.

Kept separate from ``app``/route modules so route groups can import event
names without creating an import cycle.
"""

SSE_EVENT_ASSISTANT = "assistant"
SSE_EVENT_ASSISTANT_DELTA = "assistant_delta"
SSE_EVENT_FINAL = "final"
SSE_EVENT_TOOL_CALLS = "tool_calls"
SSE_EVENT_TOOL_RESULTS = "tool_results"
SSE_EVENT_ITERATION = "iteration"
SSE_EVENT_THOUGHT = "thought"
SSE_EVENT_ERROR = "error"
SSE_EVENT_INPUT_REQUIRED = "input_required"
SSE_EVENT_INPUT_RESOLVED = "input_resolved"
SSE_EVENT_SESSION = "session"
SSE_EVENT_CONTEXT_WINDOW = "context_window"
SSE_EVENT_MODEL_CALL = "model_call"
SSE_EVENT_DELEGATE_PREFIX = "delegate_"
SSE_EVENT_DELEGATE_ASSISTANT = f"{SSE_EVENT_DELEGATE_PREFIX}{SSE_EVENT_ASSISTANT}"
SSE_EVENT_DELEGATE_FINAL = f"{SSE_EVENT_DELEGATE_PREFIX}{SSE_EVENT_FINAL}"
SSE_EVENT_DELEGATE_TOOL_CALLS = f"{SSE_EVENT_DELEGATE_PREFIX}{SSE_EVENT_TOOL_CALLS}"
SSE_EVENT_DELEGATE_TOOL_RESULTS = f"{SSE_EVENT_DELEGATE_PREFIX}{SSE_EVENT_TOOL_RESULTS}"
SSE_EVENT_DELEGATE_ITERATION = f"{SSE_EVENT_DELEGATE_PREFIX}{SSE_EVENT_ITERATION}"
SSE_EVENT_DELEGATE_THOUGHT = f"{SSE_EVENT_DELEGATE_PREFIX}{SSE_EVENT_THOUGHT}"
SSE_EVENT_DELEGATE_ERROR = f"{SSE_EVENT_DELEGATE_PREFIX}{SSE_EVENT_ERROR}"
# deprecated for lifecycle questions (stateful path uses delegate_waiting_parent)
SSE_EVENT_DELEGATE_INPUT_REQUIRED = f"{SSE_EVENT_DELEGATE_PREFIX}{SSE_EVENT_INPUT_REQUIRED}"
SSE_EVENT_DELEGATE_CONTEXT_WINDOW = f"{SSE_EVENT_DELEGATE_PREFIX}{SSE_EVENT_CONTEXT_WINDOW}"
SSE_EVENT_DELEGATE_MODEL_CALL = f"{SSE_EVENT_DELEGATE_PREFIX}{SSE_EVENT_MODEL_CALL}"
SSE_EVENT_DELEGATE_CREATED = f"{SSE_EVENT_DELEGATE_PREFIX}created"
SSE_EVENT_DELEGATE_RUNNING = f"{SSE_EVENT_DELEGATE_PREFIX}running"
SSE_EVENT_DELEGATE_WAITING_PARENT = f"{SSE_EVENT_DELEGATE_PREFIX}waiting_parent"
SSE_EVENT_DELEGATE_RESUMED = f"{SSE_EVENT_DELEGATE_PREFIX}resumed"
SSE_EVENT_DELEGATE_IDLE = f"{SSE_EVENT_DELEGATE_PREFIX}idle"
SSE_EVENT_DELEGATE_RELEASED = f"{SSE_EVENT_DELEGATE_PREFIX}released"
SSE_EVENT_DELEGATE_CANCELLED = f"{SSE_EVENT_DELEGATE_PREFIX}cancelled"
SSE_EVENT_DELEGATE_EXPIRED = f"{SSE_EVENT_DELEGATE_PREFIX}expired"
SSE_EVENT_DELEGATE_FAILED = f"{SSE_EVENT_DELEGATE_PREFIX}failed"

DELEGATE_TOOL_PREFIX = "agent__"

TRACE_ACTIVITY_EVENTS = {
    SSE_EVENT_TOOL_CALLS,
    SSE_EVENT_TOOL_RESULTS,
    SSE_EVENT_ITERATION,
    SSE_EVENT_THOUGHT,
    SSE_EVENT_ERROR,
    SSE_EVENT_INPUT_REQUIRED,
    SSE_EVENT_CONTEXT_WINDOW,
    SSE_EVENT_MODEL_CALL,
    SSE_EVENT_DELEGATE_ASSISTANT,
    SSE_EVENT_DELEGATE_FINAL,
    SSE_EVENT_DELEGATE_TOOL_CALLS,
    SSE_EVENT_DELEGATE_TOOL_RESULTS,
    SSE_EVENT_DELEGATE_ITERATION,
    SSE_EVENT_DELEGATE_THOUGHT,
    SSE_EVENT_DELEGATE_ERROR,
    SSE_EVENT_DELEGATE_INPUT_REQUIRED,
    SSE_EVENT_DELEGATE_CONTEXT_WINDOW,
    SSE_EVENT_DELEGATE_MODEL_CALL,
    SSE_EVENT_DELEGATE_CREATED,
    SSE_EVENT_DELEGATE_RUNNING,
    SSE_EVENT_DELEGATE_WAITING_PARENT,
    SSE_EVENT_DELEGATE_RESUMED,
    SSE_EVENT_DELEGATE_IDLE,
    SSE_EVENT_DELEGATE_RELEASED,
    SSE_EVENT_DELEGATE_CANCELLED,
    SSE_EVENT_DELEGATE_EXPIRED,
    SSE_EVENT_DELEGATE_FAILED,
}
